-- Call Caching Database Queries for Verification

-- 1. Check all call caching entries
SELECT 
    "WORKFLOW_EXECUTION_UUID",
    "CALL_FULLY_QUALIFIED_NAME",
    "JOB_INDEX",
    "WORKFLOW_ROOT",
    "ALLOW_RESULT_REUSE"
FROM "CALL_CACHING_ENTRY"
ORDER BY "CALL_CACHING_ENTRY_ID" DESC
LIMIT 20;

-- 2. Check call caching hash entries (what gets hashed for cache key)
SELECT 
    cce."WORKFLOW_EXECUTION_UUID",
    cce."CALL_FULLY_QUALIFIED_NAME",
    cche."HASH_KEY",
    cche."HASH_VALUE"
FROM "CALL_CACHING_ENTRY" cce
JOIN "CALL_CACHING_HASH_ENTRY" cche ON cce."CALL_CACHING_ENTRY_ID" = cche."CALL_CACHING_ENTRY_ID"
WHERE cce."WORKFLOW_EXECUTION_UUID" = 'REPLACE_WITH_WORKFLOW_ID'
ORDER BY cche."HASH_KEY";

-- 3. Check call caching result simpleton entries (cached outputs)
SELECT 
    cce."WORKFLOW_EXECUTION_UUID",
    cce."CALL_FULLY_QUALIFIED_NAME",
    ccse."SIMPLETON_KEY",
    ccse."SIMPLETON_VALUE"
FROM "CALL_CACHING_ENTRY" cce
JOIN "CALL_CACHING_SIMPLETON_ENTRY" ccse ON cce."CALL_CACHING_ENTRY_ID" = ccse."CALL_CACHING_ENTRY_ID"
WHERE cce."WORKFLOW_EXECUTION_UUID" = 'REPLACE_WITH_WORKFLOW_ID'
ORDER BY ccse."SIMPLETON_KEY";

-- 4. Check call caching detritus entries (additional metadata)
SELECT 
    cce."WORKFLOW_EXECUTION_UUID",
    cce."CALL_FULLY_QUALIFIED_NAME",
    ccde."DETRITUS_KEY",
    ccde."DETRITUS_VALUE"
FROM "CALL_CACHING_ENTRY" cce
JOIN "CALL_CACHING_DETRITUS_ENTRY" ccde ON cce."CALL_CACHING_ENTRY_ID" = ccde."CALL_CACHING_ENTRY_ID"
WHERE cce."WORKFLOW_EXECUTION_UUID" = 'REPLACE_WITH_WORKFLOW_ID'
ORDER BY ccde."DETRITUS_KEY";

-- 5. Compare hash values between two workflows (to verify same inputs = same hash)
WITH workflow_hashes AS (
    SELECT 
        cce."WORKFLOW_EXECUTION_UUID",
        cce."CALL_FULLY_QUALIFIED_NAME",
        cche."HASH_KEY",
        cche."HASH_VALUE"
    FROM "CALL_CACHING_ENTRY" cce
    JOIN "CALL_CACHING_HASH_ENTRY" cche ON cce."CALL_CACHING_ENTRY_ID" = cche."CALL_CACHING_ENTRY_ID"
    WHERE cce."WORKFLOW_EXECUTION_UUID" IN ('WORKFLOW_ID_1', 'WORKFLOW_ID_2')
)
SELECT 
    "CALL_FULLY_QUALIFIED_NAME",
    "HASH_KEY",
    "HASH_VALUE",
    COUNT(*) as hash_count
FROM workflow_hashes
GROUP BY "CALL_FULLY_QUALIFIED_NAME", "HASH_KEY", "HASH_VALUE"
HAVING COUNT(*) > 1  -- Same hash appears in multiple workflows
ORDER BY "CALL_FULLY_QUALIFIED_NAME", "HASH_KEY";

-- 6. Check execution events for call caching metadata
SELECT 
    "METADATA_KEY",
    "CALL_FQN",
    convert_from(lo_get("METADATA_VALUE"::oid), 'UTF8') AS readable_value,
    "METADATA_TIMESTAMP"
FROM "METADATA_ENTRY" 
WHERE "WORKFLOW_EXECUTION_UUID" = 'REPLACE_WITH_WORKFLOW_ID'
    AND "METADATA_KEY" LIKE '%callCaching%'
ORDER BY "METADATA_TIMESTAMP";

-- 7. Check for cache hits vs misses
SELECT 
    "METADATA_KEY",
    "CALL_FQN",
    convert_from(lo_get("METADATA_VALUE"::oid), 'UTF8') AS readable_value
FROM "METADATA_ENTRY" 
WHERE "WORKFLOW_EXECUTION_UUID" = 'REPLACE_WITH_WORKFLOW_ID'
    AND ("METADATA_KEY" = 'callCaching:hit' OR "METADATA_KEY" = 'callCaching:result')
ORDER BY "CALL_FQN";

-- 8. Check job execution times (to verify caching speed improvement)
SELECT 
    "CALL_FQN",
    "METADATA_KEY",
    convert_from(lo_get("METADATA_VALUE"::oid), 'UTF8') AS readable_value,
    "METADATA_TIMESTAMP"
FROM "METADATA_ENTRY" 
WHERE "WORKFLOW_EXECUTION_UUID" = 'REPLACE_WITH_WORKFLOW_ID'
    AND "METADATA_KEY" IN ('executionStatus', 'start', 'end')
ORDER BY "CALL_FQN", "METADATA_TIMESTAMP";

-- 9. Find matching cache entries across workflows
SELECT 
    cce1."WORKFLOW_EXECUTION_UUID" as workflow_1,
    cce2."WORKFLOW_EXECUTION_UUID" as workflow_2,
    cce1."CALL_FULLY_QUALIFIED_NAME",
    COUNT(*) as matching_hashes
FROM "CALL_CACHING_ENTRY" cce1
JOIN "CALL_CACHING_HASH_ENTRY" cche1 ON cce1."CALL_CACHING_ENTRY_ID" = cche1."CALL_CACHING_ENTRY_ID"
JOIN "CALL_CACHING_HASH_ENTRY" cche2 ON cche1."HASH_KEY" = cche2."HASH_KEY" AND cche1."HASH_VALUE" = cche2."HASH_VALUE"
JOIN "CALL_CACHING_ENTRY" cce2 ON cche2."CALL_CACHING_ENTRY_ID" = cce2."CALL_CACHING_ENTRY_ID"
WHERE cce1."WORKFLOW_EXECUTION_UUID" != cce2."WORKFLOW_EXECUTION_UUID"
    AND cce1."CALL_FULLY_QUALIFIED_NAME" = cce2."CALL_FULLY_QUALIFIED_NAME"
GROUP BY cce1."WORKFLOW_EXECUTION_UUID", cce2."WORKFLOW_EXECUTION_UUID", cce1."CALL_FULLY_QUALIFIED_NAME"
ORDER BY matching_hashes DESC;

-- 10. Performance comparison query
SELECT 
    "WORKFLOW_EXECUTION_UUID",
    "CALL_FQN",
    MIN(CASE WHEN "METADATA_KEY" = 'start' THEN "METADATA_TIMESTAMP" END) as start_time,
    MAX(CASE WHEN "METADATA_KEY" = 'end' THEN "METADATA_TIMESTAMP" END) as end_time,
    MAX(CASE WHEN "METADATA_KEY" = 'end' THEN "METADATA_TIMESTAMP" END) - 
    MIN(CASE WHEN "METADATA_KEY" = 'start' THEN "METADATA_TIMESTAMP" END) as duration
FROM "METADATA_ENTRY" 
WHERE "WORKFLOW_EXECUTION_UUID" IN ('WORKFLOW_ID_1', 'WORKFLOW_ID_2')
    AND "METADATA_KEY" IN ('start', 'end')
    AND "CALL_FQN" IS NOT NULL
GROUP BY "WORKFLOW_EXECUTION_UUID", "CALL_FQN"
ORDER BY "CALL_FQN", "WORKFLOW_EXECUTION_UUID";